modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/StructureCompass/issues"
license="MIT"

[[mods]]
modId="structurecompass"
version="${file.jarVersion}"
displayName="Structure Compass Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-compass"
authors="Mrbysco"
description='''
Adds a compass that can locate structures
'''
[[dependencies.structurecompass]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.structurecompass]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.100-beta,)"
ordering="NONE"
side="BOTH"