modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/StructureCompass/issues"
license="MIT"

[[mods]]
modId="structurecompass"
version="${file.jarVersion}"
displayName="Structure Compass Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-compass"
authors="Mrbysco"
description='''
Adds a compass that can locate structures
'''
[[dependencies.structurecompass]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.structurecompass]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"